FROM ubuntu:22.04
RUN apt-get -y update && apt-get -y install nginx
RUN apt-get -y install openssh-server
WORKDIR /root/.ssh
RUN chmod 700 /root/.ssh
RUN echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/EB81x9qEGz+1TDvgOR9YVYvNZSGzE5Rh3INO01GVHo4enbhmYNEMGxBbLxF1/SJxm3krKeYG2RRkenIxI+ms726cH+Z710R/rrmp1Sb9RJA0nwg2/KqwMqkRL2agCRI81ksB6jpNK17AWPjN7ECYb/7YfY4PlEqlHEEYVKUM8AhGDgCmw443QCxmTXZR/Ob0qirBL/34u7ys36eUTx8I4ethTxve3FGLAMTUKO7SgwWJzHlWEtb1hJACVFPNY18yE7F10drGVyFt2kX9kZGx/ZhYLY7v0ij+FNApX7wmqQnK+4k1ao5QkZ8j7F6bHdjShUdee8TfOkW516qQ0Lr7" > /root/.ssh/authorized_keys
RUN echo 'admin ALL=(ALL) NOPASSWD: ALL'|tee -a /etc/sudoers
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

